### ISSUE TITLE
This repo should say what the plugin does

### ISSUE THREAD

**Issue by reagle** [quicksilver/zoom.us#2]
I see there's a plugin, but what does it do?

**Comment by skurfer** [comment]
Every plug-in should have documentation that can be viewed in Quicksilver’s plug-in preferences.

The source of that documentation can also be found in the repo for each plug-in. For example…

https://github.com/quicksilver/zoom.us/blob/master/Documentation.mdown

**Comment by pjrobertson** [comment]
Skurfer's link above gives more info on this specific plugin.

I'll close this issue now, and disable issue tracking on this repo. In the future, please report issues on the quicksilver/quicksilver repo
